### ISSUE TITLE
Button Funny Business.

### ISSUE THREAD

**Issue by rossdotparker** [adrientremblay/helpdesk#4]
When we added a second issue, we got two view buttons in the second row, and then when we assigned the first issue to a technician, the assign button on the second issue disappeared.

**Comment by raynichc** [comment]
I can't seem to be able to recreate the issue.

**Comment by rossdotparker** [comment]
But you closed it before I could try and provide some recreation steps!

On Thu, Jan 22, 2015 at 1:03 PM, raynichc <notifications@github.com> wrote:

> Closed #4 <https://github.com/adrientremblay/helpdesk/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrientremblay/helpdesk/issues/4#event-222808650>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--
